### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by 396559551** [vita-epfl/trajnetplusplusbaselines#11]
Hi，
When I  run **trajnet_evaluator.py** after training with cuda.
**RuntimeError: CUDA error: out of memory**

 Is it my personal problem? or   Only can I train this code on CPU?

**Comment by 396559551** [comment]
> Hi,
> Could you provide the entire command you are trying to execute on the terminal?

The problem is solved, the reason is that my computer's virtual memory is not enough
thanks~
